version: '3.8'

services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    ports:
      - "1883:1883"         # MQTT communication port
      - "9001:9001"         # WebSockets port (for access via browser)
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - app-network
  
  webserver:
    build:
      context: ./flask-app
      dockerfile: Dockerfile
    container_name: flask-webserver
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - DATABASE_URL=postgresql://admin:dbpass@db:5432/shelves-db
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=shelves-db
    ports:
      - "5432:5432"
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - app-network


volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge